-- This file is generated by the GTARP boot module. (Hash: 4e20844b2a5a459b2f3d2ad94ef4d66d1c63a3c859f086cf719bfe346ba84202)
fx_version 'cerulean'
game 'gta5'

name 'callbacks'
author 'trackz'
description 'GTARP Boilerplate'

client_scripts { 'client/*' }
shared_scripts { 'shared/*' }
server_scripts { 'server/*' }
